spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/commandes_dev}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.polytech.commandes: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE